<a href="https://colab.research.google.com/github/astrovishalthakur/MachineLearning/blob/main/AccuracyEvaluation/ClassificationMetrics.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
! pip install kaggle

In [3]:
from google.colab import drive
drive.mount("/content/drive")

Mounted at /content/drive


In [4]:
! mkdir ~/.kaggle

In [6]:
! cp "/content/drive/MyDrive/kaggle/kaggle.json" ~/.kaggle/kaggle.json

In [7]:
! kaggle datasets download -d ronitf/heart-disease-uci

  0% 0.00/3.40k [00:00<?, ?B/s]
100% 3.40k/3.40k [00:00<00:00, 6.75MB/s]


In [8]:
! unzip heart-disease-uci.zip

Archive:  heart-disease-uci.zip
  inflating: heart.csv               


In [9]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt


In [10]:
df = pd.read_csv("heart.csv")

In [11]:
df.head()

age  sex  cp  trestbps  chol  fbs  ...  exang  oldpeak  slope  ca  thal  target
0   63    1   3       145   233    1  ...      0      2.3      0   0     1       1
1   37    1   2       130   250    0  ...      0      3.5      0   0     2       1
2   41    0   1       130   204    0  ...      0      1.4      2   0     2       1
3   56    1   1       120   236    0  ...      0      0.8      2   0     2       1
4   57    0   0       120   354    0  ...      1      0.6      2   0     2       1

[5 rows x 14 columns]

In [12]:
from sklearn.model_selection import train_test_split

In [13]:
X = df.iloc[:,0:-2]
y = df.iloc[:,-1]

In [14]:
X.head()

age  sex  cp  trestbps  chol  ...  thalach  exang  oldpeak  slope  ca
0   63    1   3       145   233  ...      150      0      2.3      0   0
1   37    1   2       130   250  ...      187      0      3.5      0   0
2   41    0   1       130   204  ...      172      0      1.4      2   0
3   56    1   1       120   236  ...      178      0      0.8      2   0
4   57    0   0       120   354  ...      163      1      0.6      2   0

[5 rows x 12 columns]

In [15]:
y.head()

0    1
1    1
2    1
3    1
4    1
Name: target, dtype: int64

In [16]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=2)

In [17]:
from sklearn.linear_model import LogisticRegression
from sklearn.tree import DecisionTreeClassifier

In [18]:
lr = LogisticRegression()
dt = DecisionTreeClassifier()

In [19]:
lr.fit(X_train, y_train)
dt.fit(X_train, y_train)

/usr/local/lib/python3.7/dist-packages/sklearn/linear_model/_logistic.py:818: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  extra_warning_msg=_LOGISTIC_SOLVER_CONVERGENCE_MSG,


DecisionTreeClassifier()

In [20]:
y_pred1 = lr.predict(X_test)
y_pred2 = dt.predict(X_test)

# Calculating accuracy

In [21]:
from sklearn.metrics import accuracy_score, confusion_matrix

print("Accuracy of Logistic Regression", accuracy_score(y_test, y_pred1))
print("Accuracy of Decision Tree", accuracy_score(y_test, y_pred2))

Accuracy of Logistic Regression 0.9016393442622951
Accuracy of Decision Tree 0.7868852459016393


# Confusion Matrix

<img src="https://cdn-images-1.medium.com/max/950/1*PPgItHcPSaskyjLMWFC-Kw.png" width=300px>

In [25]:
confusion_matrix(y_test, y_pred1)

array([[26,  6],
       [ 0, 29]])

In [28]:
tn, fp, fn, tp = confusion_matrix(y_test, y_pred2).ravel()

print(f"TN {tn} \nTP {tp} \nFP {fp} \nFN {fn}")
confusion_matrix(y_test, y_pred2)   

TN 22 
TP 26 
FP 10 
FN 3


array([[22, 10],
       [ 3, 26]])

In [29]:
# it means sklearn's way of representing cm is
np.array([["TN", "FP"], ["FN", "TP"]])

array([['TN', 'FP'],
       ['FN', 'TP']], dtype='<U2')

# Precision Recall F1Score

In [30]:
from sklearn.metrics import recall_score, precision_score, f1_score

In [34]:
print("For Logistic Regression\n")
print(f"Recall {recall_score(y_test, y_pred1)}\nPrecision {precision_score(y_test, y_pred1)}\nF1-Score {f1_score(y_test, y_pred1)}")
print('''

''')
print("For Decision Tree\n")
print(f"Recall {recall_score(y_test, y_pred2)}\nPrecision {precision_score(y_test, y_pred2)}\nF1-Score {f1_score(y_test, y_pred2)}")

For Logistic Regression

Recall 1.0
Precision 0.8285714285714286
F1-Score 0.90625



For Decision Tree

Recall 0.896551724137931
Precision 0.7222222222222222
F1-Score 0.7999999999999999


## also, in Binary Classification, we focus more on the positive class.
## But in reality, we calculate metrices like precision - recall for both classes i.e. 0 and 1, but only show precision and recall value of positive class. To see Recall or precision values of all classes, set average = None

In [43]:
# normally
precision_score(y_test, y_pred1)

0.8285714285714286

In [42]:
# To see all classes
precision_score(y_test, y_pred1, average=None)

array([1.        , 0.82857143])

# Classification Report

In [22]:
from sklearn.metrics import classification_report
print(classification_report(y_test, y_pred1))

              precision    recall  f1-score   support

           0       1.00      0.81      0.90        32
           1       0.83      1.00      0.91        29

    accuracy                           0.90        61
   macro avg       0.91      0.91      0.90        61
weighted avg       0.92      0.90      0.90        61



In [38]:
print(classification_report(y_test, y_pred2))

              precision    recall  f1-score   support

           0       0.88      0.69      0.77        32
           1       0.72      0.90      0.80        29

    accuracy                           0.79        61
   macro avg       0.80      0.79      0.79        61
weighted avg       0.80      0.79      0.79        61



### we can get average precision and recall scores of multi class classification, just put value of average parameter = 
1. "macro" for normal average
2. "weighted" for weighted average

In [45]:
precision_score(y_test, y_pred1, average=None)

array([1.        , 0.82857143])

In [44]:
# To see all classes
precision_score(y_test, y_pred1, average="macro")

0.9142857142857144

In [46]:
precision_score(y_test, y_pred1, average="weighted")

0.9185011709601872