<a href="https://colab.research.google.com/github/astrovishalthakur/MachineLearning/blob/main/SklearnFeatures/Pipelining/WithoutPipeline/PredictWithoutPipeline.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import pickle
import numpy as np


In [2]:
ohe_sex = pickle.load(open("ohe_sex.pkl", "rb"))
ohe_embarked = pickle.load(open("ohe_embarked.pkl", "rb"))
clf = pickle.load(open("clf.pkl", "rb"))

In [3]:
# Assume user input 
#Pclass/gender/age.SibSp/Parch/Fare/Embarked

test_input = np.array([2, "male", 31.0, 0, 0, 10.5, "S"], dtype=object).reshape(1,7)

In [4]:
test_input

array([[2, 'male', 31.0, 0, 0, 10.5, 'S']], dtype=object)

In [6]:
test_input_sex = ohe_sex.transform(test_input[:,1].reshape(1, 1))

/usr/local/lib/python3.7/dist-packages/sklearn/base.py:451: UserWarning: X does not have valid feature names, but OneHotEncoder was fitted with feature names
  "X does not have valid feature names, but"


In [7]:
test_input_sex

array([[0., 1.]])

In [8]:
ohe_sex.get_feature_names()

/usr/local/lib/python3.7/dist-packages/sklearn/utils/deprecation.py:87: FutureWarning: Function get_feature_names is deprecated; get_feature_names is deprecated in 1.0 and will be removed in 1.2. Please use get_feature_names_out instead.
  warnings.warn(msg, category=FutureWarning)


array(['x0_female', 'x0_male'], dtype=object)

In [9]:
test_input_embarked = ohe_embarked.transform(test_input[:, -1].reshape(1, 1))

In [10]:
test_input_embarked

array([[0., 0., 1.]])

In [11]:
ohe_embarked.get_feature_names()

/usr/local/lib/python3.7/dist-packages/sklearn/utils/deprecation.py:87: FutureWarning: Function get_feature_names is deprecated; get_feature_names is deprecated in 1.0 and will be removed in 1.2. Please use get_feature_names_out instead.
  warnings.warn(msg, category=FutureWarning)


array(['x0_C', 'x0_Q', 'x0_S'], dtype=object)

In [12]:
test_input_age = test_input[:,2].reshape(1, 1)

In [13]:
test_input_transformed = np.concatenate((test_input[:,[0, 3, 4, 5]], test_input_age, test_input_sex, test_input_embarked), axis=1)

In [21]:
test_input_transformed

array([[2, 0, 0, 10.5, 31.0, 0.0, 1.0, 0.0, 0.0, 1.0]], dtype=object)

In [15]:
clf.predict(test_input_transformed)

array([0])